Asp.netMVCQLBanVeXeKhach/Models/Vitrighe.cs
using System;
using System.Collections.Generic;

namespace Asp.netMVCQLBanVeXeKhach.Models
{
    public partial class Vitrighe
    {
        public Vitrighe()
        {
            VeXes = new HashSet<VeXe>();
        }

        public int IdVitri { get; set; }
        public string Bienso { get; set; } = null!;
        public string? Tenvitri { get; set; }
        public bool? Trangthai { get; set; }

        public virtual Xe BiensoNavigation { get; set; } = null!;
        public virtual ICollection<VeXe> VeXes { get; set; }
    }
}

Asp.netMVCQLBanVeXeKhach/Controllers/ViTriGheController.cs
using Asp.netMVCQLBanVeXeKhach.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Asp.netMVCQLBanVeXeKhach.Controllers
{
    public class ViTriGheController : Controller
    {
        private readonly QLDatVeContext _context;

        public ViTriGheController(QLDatVeContext context)
        {
            _context = context;
        }

        // GET: ViTriGhe
        public IActionResult Index()
        {
            var vitriGhes = _context.Vitrighes.Include(v => v.BiensoNavigation).ToList();
            return View(vitriGhes);
        }

        public IActionResult Details(int id)
        {
            var vitriGhe = _context.Vitrighes
                .Include(v => v.BiensoNavigation)
                .FirstOrDefault(v => v.IdVitri == id);

            if (vitriGhe == null)
            {
                return NotFound();
            }

            return View(vitriGhe);
        }


        public IActionResult Create()
        {
                 ViewData["BiensoList"] = new SelectList(_context.Xes, "Bienso", "Bienso");

            return View();
        }

        // POST: ViTriGhe/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("IdVitri,Bienso,Tenvitri,Trangthai")] Vitrighe vitriGhe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vitriGhe);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            ViewData["BiensoList"] = new SelectList(_context.Xes, "Bienso", "Bienso", vitriGhe.Bienso);
            return View(vitriGhe);
        }


    
        //vị trí ghế k có sửa bởi vì vị trí ghế hoạt động dựa vào đặt vé ở chuyến xe
       
        

 
        public IActionResult Delete(int id)
        {
            var vitriGhe = _context.Vitrighes.Find(id);
            if (vitriGhe == null)
            {
                return NotFound();
            }

            return View(vitriGhe);
        }

 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var vitriGhe = _context.Vitrighes.Find(id);
            if (vitriGhe != null)
            {
                _context.Vitrighes.Remove(vitriGhe);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool VitrigheExists(int id)
        {
            return _context.Vitrighes.Any(e => e.IdVitri == id);
        }
    }
}

Asp.netMVCQLBanVeXeKhach/Controllers/VitrighesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asp.netMVCQLBanVeXeKhach.Models;

namespace Asp.netMVCQLBanVeXeKhach.Controllers
{
    public class VitrighesController : Controller
    {
        private readonly QLDatVeContext _context;

        public VitrighesController(QLDatVeContext context)
        {
            _context = context;
        }

        // GET: Vitrighes
        public async Task<IActionResult> Index()
        {
            var qLDatVeContext = _context.Vitrighes.Include(v => v.BiensoNavigation);
            return View(await qLDatVeContext.ToListAsync());
        }

        // GET: Vitrighes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vitrighes == null)
            {
                return NotFound();
            }

            var vitrighe = await _context.Vitrighes
                .Include(v => v.BiensoNavigation)
                .FirstOrDefaultAsync(m => m.IdVitri == id);
            if (vitrighe == null)
            {
                return NotFound();
            }

            return View(vitrighe);
        }

        // GET: Vitrighes/Create
        public IActionResult Create()
        {
            ViewData["Bienso"] = new SelectList(_context.Xes, "Bienso", "Bienso");
            return View();
        }

        // POST: Vitrighes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVitri,Bienso,Tenvitri,Trangthai")] Vitrighe vitrighe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vitrighe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bienso"] = new SelectList(_context.Xes, "Bienso", "Bienso", vitrighe.Bienso);
            return View(vitrighe);
        }

        // GET: Vitrighes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vitrighes == null)
            {
                return NotFound();
            }

            var vitrighe = await _context.Vitrighes.FindAsync(id);
            if (vitrighe == null)
            {
                return NotFound();
            }
            ViewData["Bienso"] = new SelectList(_context.Xes, "Bienso", "Bienso", vitrighe.Bienso);
            return View(vitrighe);
        }

        // POST: Vitrighes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVitri,Bienso,Tenvitri,Trangthai")] Vitrighe vitrighe)
        {
            if (id != vitrighe.IdVitri)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vitrighe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VitrigheExists(vitrighe.IdVitri))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bienso"] = new SelectList(_context.Xes, "Bienso", "Bienso", vitrighe.Bienso);
            return View(vitrighe);
        }

        // GET: Vitrighes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vitrighes == null)
            {
                return NotFound();
            }

            var vitrighe = await _context.Vitrighes
                .Include(v => v.BiensoNavigation)
                .FirstOrDefaultAsync(m => m.IdVitri == id);
            if (vitrighe == null)
            {
                return NotFound();
            }

            return View(vitrighe);
        }

        // POST: Vitrighes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vitrighes == null)
            {
                return Problem("Entity set 'QLDatVeContext.Vitrighes'  is null.");
            }
            var vitrighe = await _context.Vitrighes.FindAsync(id);
            if (vitrighe != null)
            {
                _context.Vitrighes.Remove(vitrighe);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VitrigheExists(int id)
        {
          return (_context.Vitrighes?.Any(e => e.IdVitri == id)).GetValueOrDefault();
        }
    }
}

Asp.netMVCQLBanVeXeKhach/Views/Vitrighes/Create.cshtml
@model Asp.netMVCQLBanVeXeKhach.Models.Vitrighe

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Vitrighe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdVitri" class="control-label"></label>
                <input asp-for="IdVitri" class="form-control" />
                <span asp-validation-for="IdVitri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bienso" class="control-label"></label>
                <select asp-for="Bienso" class ="form-control" asp-items="ViewBag.Bienso"></select>
            </div>
            <div class="form-group">
                <label asp-for="Tenvitri" class="control-label"></label>
                <input asp-for="Tenvitri" class="form-control" />
                <span asp-validation-for="Tenvitri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trangthai" class="control-label"></label>
                <input asp-for="Trangthai" class="form-control" />
                <span asp-validation-for="Trangthai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Asp.netMVCQLBanVeXeKhach/Views/Vitrighes/Delete.cshtml
@model Asp.netMVCQLBanVeXeKhach.Models.Vitrighe

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Xóa</h1>

<h3>Bạn có muốn xóa ghế? </h3>
<div>
    <h4>Vitrighe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tenvitri)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tenvitri)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BiensoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BiensoNavigation.Bienso)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdVitri" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="ViTriGhe">Trở về</a>
    </form>
</div>

Asp.netMVCQLBanVeXeKhach/Views/Vitrighes/Details.cshtml
@model Asp.netMVCQLBanVeXeKhach.Models.Vitrighe

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Vitrighe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tenvitri)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tenvitri)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BiensoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BiensoNavigation.Bienso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdVitri">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Asp.netMVCQLBanVeXeKhach/Views/Vitrighes/Edit.cshtml
@model Asp.netMVCQLBanVeXeKhach.Models.Vitrighe

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Chỉnh sửa vị trí ghế</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdVitri" />
            <div class="form-group">
                <label asp-for="Bienso" class="control-label"></label>
                <select asp-for="Bienso" class="form-control" asp-items="ViewBag.Bienso"></select>
                <span asp-validation-for="Bienso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tenvitri" class="control-label"></label>
                <input asp-for="Tenvitri" class="form-control" />
                <span asp-validation-for="Tenvitri" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trangthai" class="control-label"></label>
                <input asp-for="Trangthai" class="form-control" />
                <span asp-validation-for="Trangthai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

Asp.netMVCQLBanVeXeKhach/Views/Vitrighes/Index.cshtml
@model IEnumerable<Asp.netMVCQLBanVeXeKhach.Models.Vitrighe>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tenvitri)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trangthai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BiensoNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tenvitri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trangthai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BiensoNavigation.Bienso)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdVitri">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdVitri">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdVitri">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>